name: NetCore-Geocodificador-CI
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Geocodificador/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/Geocodificador*.csproj'
    displayName: 'Restore Nuget Packages'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/Geocodificador*.csproj'
      arguments: '--no-restore'
    displayName: 'Build projects'

  # - task: DotNetCoreCLI@2 TODO
  #   inputs:
  #     command: 'test'
  #     projects: '**/*Test.csproj'
  #     arguments: '--no-restore --no-build'
  #   displayName: 'Run Tests'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '**/Geocodificador.csproj'
      arguments: '--configuration $(buildConfiguration) --no-restore'
      modifyOutputPath: false
    displayName: 'Publish Geocodificador'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
